name: Feature Push

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  build-and-publish:
    name: Docker Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
        